const ActionTypes = {
  GET_INVOICE_REQUEST: "GET_INVOICE_REQUEST",
  GET_INVOICE_SUCCESS: "GET_INVOICE_SUCCESS",
  GET_INVOICE_FAIL: "GET_INVOICE_FAIL",

  DELETE_CUSTOMER_SUCCESS: "DELETE_CUSTOMER_SUCCESS",
  DELETE_CUSTOMER_FAIL: "DELETE_CUSTOMER_FAIL",

  ADD_CUSTOMER_SUCCESS: "ADD_CUSTOMER_SUCCESS",
  ADD_CUSTOMER_FAIL: "ADD_CUSTOMER_FAIL",

  EDIT_CUSTOMER_SUCCESS: "EDIT_CUSTOMER_SUCCESS",
  EDIT_CUSTOMER_FAIL: "EDIT_CUSTOMER_FAIL",
};

export default ActionTypes;
